name: Deploy Frontend

on:
  push:
    branches:
      - deploy-fe

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Connect to VPS & Deploy Frontend
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |                 
            echo "Stopping existing frontend container..."
            cd /var/www/frontend
            sudo docker-compose down
            
            echo "ğŸ“¦ Pulling latest frontend code..."
            git pull origin deploy-fe
            
            echo "ğŸ”§ Building frontend container..."
            sudo docker-compose build --no-cache
            
            echo "ğŸš€ Starting frontend container..."
            sudo docker-compose up -d
            
            echo "ğŸ”„ Restarting Nginx..."
            sudo systemctl restart nginx
            
            echo "âœ”ï¸ Frontend Deployment Completed Successfully! "